### PR TITLE
feat(examples): adds attribute `ls,add,rm` cmds

### PR DESCRIPTION
**Pull request by dmihalcik-virtru**
- `example attribute ...`
  - `ls [-N http://name.space]`: List all attributes and values, or all in the requested namespace
   - `add -a https://name.space/attr/attrname -v "v1 v2 v3" [-r anyof]` Defines and attribute
   - `rm -a https://a.b/attr/n [-v "just the values to remove"]`

### CODE REVIEW

**Comment by jrschumacher** [comment]
@dmihalcik-virtru this seems like its a duplication of opentdf/otdfctl which is powering the opentdf CLI administration as well as downstream implementations. Is there a reason why we are rebuilding the wheel?

**Comment by dmihalcik-virtru** [comment]
> @dmihalcik-virtru this seems like its a duplication of https://github.com/opentdf/otdfctl which is powering the opentdf CLI administration as well as downstream implementations. Is there a reason why we are rebuilding the wheel?
> 
> Concern is that we'll have to maintain this example if people start using it to manage their platforms rather than pointing to the CLI.

This is intended as example code and for use with integration tests. We do not publish releases of `examples` and do not document it as such. `otdfctl` is intended to be production quality, and likely not incorporate such features as are present here that are experimental or dangerous

**Comment by dmihalcik-virtru** [comment]
As to specific motivations for doing this now, we need integration tests here that bring up multiple copies of the core services to validate splitting and sharing key data across different servers, validating failure modes when attribute defintiions disagree, and more. otdfctl is difficult to use with unreleased features, as it is hosted in a different repo. Additionally, it isn't clear that we want to expose *all* features through the CLI before vetting them as much as possible.

**Review by pflynn-virtru — APPROVED** [review]

**Comment by strantalis** [comment]
@dmihalcik-virtru Is otdfctl missing features that a consumer would take advantage of?

**Comment by jrschumacher** [comment]
> Additionally, it isn't clear that we want to expose all features through the CLI before vetting them as much as possible.

One nice feature of cobra is that we can use the `hidden` flag to prevent showing it in the help menu. This would allow us to experiment without supporting it. 

Also, I'm fine using build tags so we can build experimental versions of the CLI and stable versions. This is especially true since we tend to put the CLI cobra instructions in separate files.

**Comment by dmihalcik-virtru** [comment]
> One nice feature of cobra is that we can use the `hidden` flag to prevent showing it in the help menu. This would allow us to experiment without supporting it. 

We may want to do this soon for jwk set management, or other emerging features. However, without moving `otdfctl` repo into this one, it will be difficult to do it on a branch; it would still either require coordinating work there with a branch from a PR here, or something more complex where we check out a branch from there and add it to the workspace after checkout (or look into a submodule)

**Pull request merged**
