### PR TITLE
feat(policy): add unsafe service protos and unsafe service proto Go gencode

### PR DESCRIPTION
**Pull request by jakedoublev**
First PR related to #115

### CODE REVIEW

**Comment by jrschumacher** [comment]
@jakedoublev I'm wondering if we want the client to return some value to verify they was to perform this destructive behavior. For instance if you want to delete you need to provide the id and the name.

**Comment by jrschumacher** [comment]
Then we can just pass the user's input from CLI or web directly to the server. No need for user clients to add that layer.

**Comment by jakedoublev** [comment]
> @jakedoublev I'm wondering if we want the client to return some value to verify they was to perform this destructive behavior. For instance if you want to delete you need to provide the id and the name.

That's a good idea @jrschumacher. I think the behavior that would guard against is a mistaken UUID being utilized to delete the policy object. Some other options would be:
1. requiring passage of parent/children (i.e. provide definition ids under the namespace when deleting a namespace, and values under a definition when deleting a definition)
2. adding another param like `acknowledgeRisk: boolean`

Of those, I think 1 is too burdensome and 2 is awkward and clunky. Your suggestion is the best to prevent a mistake and for consumer DX/UX downstream.

**Comment by jakedoublev** [comment]
I think `reactivation` is okay with just an `id` because it is not cascading (like `delete`), which is most dangerous, and unsafe `update`s are likely also fine with just the `id` and the mutations.

The protos ensure gencode in each language and the HTTP path behind `/unsafe` will indicate the danger of these mutations.

**Review by jrschumacher — APPROVED** [review]

**Pull request merged**
