### PR TITLE
chore(ci): disable issue association requirement

### PR DESCRIPTION
**Pull request by strantalis**

### CODE REVIEW

**Review by jakedoublev — APPROVED** [review]

**Comment by jentfoo** [comment]
Is there any back story on why this being disabled, or what the plan is here?

**Comment by strantalis** [comment]
@jentfoo 
> Is there any back story on why this being disabled, or what the plan is here?

We are moving back to Jira.

**Comment by jentfoo** [comment]
Is there any plans to build a similar enforcement to Jira tickets?  If so loop me in and I am happy to help

**Comment by strantalis** [comment]
> Is there any plans to build a similar enforcement to Jira tickets? If so loop me in and I am happy to help

Not at this time. But I am open to it.

**Pull request merged**
