### PR TITLE
wrapped h2 in CORS instead of h to enable CORS on GRPC

### PR DESCRIPTION
**Pull request by davidbkirk**
CORS issues from COP to platform when on different domains

@davidmmartin5 @danny-holloway

### CODE REVIEW

**Comment by stoneb344** [comment]
CORS issue in OpenShift with requests to different subdomain:
Screenshot 2024-08-14 at 3 26 36 PM

**Comment by jakedoublev** [comment]
Does setting the [configured CORS config](https://github.com/opentdf/platform/blob/main/opentdf-dev.yaml#L79-L80) resolve this?

**Comment by davidbkirk** [comment]
@stoneb344  https://github.com/opentdf/platform/blob/2b7093136f6af1b6a86e613c095cefe403c9a06c/opentdf-example.yaml#L67-L92

**Comment by stoneb344** [comment]
Setting those values resolved the CORS error. Thanks for pointing it out

**Comment by stoneb344** [comment]
With `server.cors.enabled: true` and `server.cors.allowedorigins:` including an entry for the COP origin (https://cop-demox.apps.dsp.shp.virtru.us), we encounter a separate CORS issue regarding a preflight redirect:

Screenshot 2024-08-16 at 1 04 42 PM

**Pull request closed without merging**
